[WIP] Don't delete MemoryPlanningLine referenced in outputs?
pytorch/torchdynamo pull request #1029
Opened 2022-08-25 21:10 UTC by voznesenskym

2022-08-25 21:46 UTC, voznesenskym commented on torchinductor/codegen/wrapper.py
> +        def extract_name(out):
this feels gross, I wonder if it would be better served as a util on ir.py?

2022-08-25 23:49 UTC, voznesenskym commented
Benchmarking this now

2022-08-26 00:14 UTC, voznesenskym commented
Bench seems fine.

2022-08-26 03:38 UTC, jansel requested changes

2022-08-26 03:38 UTC, jansel commented on torchinductor/codegen/wrapper.py
> +        out_names = [extract_name(out) for out in V.graph.graph_outputs]
We collect names of all outputs here:
https://github.com/pytorch/torchdynamo/blob/da8bb9a875beede7b721425087d06ebae7bc76f8/torchinductor/scheduler.py#L849
and, here:
https://github.com/pytorch/torchdynamo/blob/da8bb9a875beede7b721425087d06ebae7bc76f8/torchinductor/scheduler.py#L600

I'd suggest adding a function like:
```
V.graph.get_output_names()
````

That combines the 3 places

2022-08-26 03:38 UTC, jansel commented on torchinductor/codegen/wrapper.py
> +                if self.lines[-1].node.name not in out_names:
Just put this in the condition of the while loop above to be more concise

2022-08-26 04:11 UTC, jansel commented on torchinductor/graph.py
> +    def get_output_names(self):
Update the other uses to use this

2022-08-26 04:33 UTC, jansel approved these changes

2022-08-29 20:07 UTC, merged