Generate TARGETS file for inductor kernels in fbcode
pytorch/torchdynamo pull request #1405
Opened 2022-09-28 19:29 UTC by bertmaher

Fixes #1097

2022-09-29 05:43 UTC, jansel reviewed
`make format` should fix lint issues

2022-09-29 05:43 UTC, jansel commented on torchinductor/debug.py
> +            fd.write("""
Suggest `textwrap.dedent()` so you can indent this a bit nicer.

2022-09-29 06:23 UTC, voznesenskym requested changes
We are missing the C++ side of things here (Headers, .so). I am also not sure we generate a single file. a `glob` rule for the out dir may cover things better.

Where is it writing TARGETS to atm?

2022-10-15 21:14 UTC, jansel commented
We have migrated `torchdynamo` to `torch._dynamo` and will use the `pytorch/pytorch` repo for future development.  Please resubmit this PR to https://github.com/pytorch/pytorch/

More details and instructions to port this PR over can be found in https://github.com/pytorch/torchdynamo/issues/1588

2022-10-15 21:14 UTC, closed without merging