Wrap torch.profiler.* with AutogradProfilerContextWrapperVariable
pytorch/torchdynamo pull request #1542
Opened 2022-10-07 22:38 UTC by yanboliang

2022-10-07 22:44 UTC, msaroufim approved these changes

2022-10-07 22:47 UTC, voznesenskym requested changes
If autograd profiler is going to be used for more than autograd, please rename it

2022-10-07 23:11 UTC, mlazos approved these changes

2022-10-07 23:19 UTC, voznesenskym approved these changes
Lgtm ty :)

2022-10-08 00:08 UTC, msaroufim approved these changes

2022-10-08 01:40 UTC, merged