Skip non tensor
pytorch/torchdynamo pull request #171
Opened 2022-04-25 19:03 UTC by anijain2305

Starting to work on #69 

This remove pytest module related errors while running in PyTorch.

~~~
pytest -v -s test/test_torch.py::TestTorch::test_RNG_after_pickle
~~~

The PR is draft because
* Looking for initial reviews to ensure that direction is good. (cc @jansel)
* Do thorough performance testing with TorchBench on inference and training to ensure that important frames are not missed.
* Do thorough testing with PyTorch tests to see if we need can be more aggressive in skipping more frames.

2022-04-25 19:23 UTC, jansel requested changes
A few minor comments, but overall approach looks good.

2022-04-25 19:23 UTC, jansel commented on torchdynamo/convert_frame.py
> +    for _, value in frame.f_locals.items():
```suggestion
    for value in frame.f_locals.values():
```

2022-04-25 19:23 UTC, jansel commented on torchdynamo/convert_frame.py
> +    for _, value in frame.f_globals.items():
`frame.f_code.co_names` contains a list of all the global variable names this function could read.  

So we don't actually need to iterate over all globals, just the ones that the code could reference.

2022-04-25 19:26 UTC, jansel commented on torchdynamo/convert_frame.py
> +        if inspect.ismodule(value) and value.__name__ in allowed_modules:
For this test, we might want to reuse some code from `allowed_functions.py`

2022-05-16 18:31 UTC, anijain2305 commented
Duplicate at https://github.com/pytorch/torchdynamo/pull/248

2022-05-16 18:31 UTC, closed without merging