Prioritize class method if there is duplicated attribute name
pytorch/torchdynamo pull request #278
Opened 2022-05-24 01:12 UTC by yanboliang

Fix https://github.com/pytorch/torchdynamo/issues/276

2022-05-24 01:20 UTC, yanboliang commented on torchdynamo/variables/nn_module.py
> +            class_member = False
I still use ```class_member``` but I think it's a confusing name, ```object_member``` should be better? Correct me if I'm wrong. @jansel

2022-05-24 02:20 UTC, jansel commented
So normal python objects have the opposite behavior
```
>>> class Foo:
...   def __init__(self):
...     self.hook = lambda: "on the object"
...   def hook(self):
...     return "on the class"
... 
>>> Foo().hook()
'on the object'
>>> 
```


Trying a bit more with `nn.Modules`:
```
>>> class Bar(torch.nn.Module):
...   def __init__(self):
...     super().__init__()
...     self.hook1 = torch.nn.ReLU()
...     self.hook2 = lambda: "on the object"
...     self.hook3 = "on the object"
...   def hook1(self):
...     return "on the class"
...   def hook2(self):
...     return "on the class"
...   def hook3(self):
...     return "on the class"
... 
>>> Bar().hook1
<bound method Bar.hook1 of Bar(
  (hook1): ReLU()
)>
>>> Bar().hook2()
'on the object'
>>> Bar().hook3
'on the object'
>>> 
```

As far as I can tell the object one wins.  What is different in this case?

2022-05-24 02:30 UTC, jansel requested changes
We should update the logic to match what is in the linked comment above.

2022-05-25 00:15 UTC, yanboliang commented
See more details at https://github.com/pytorch/torchdynamo/issues/276#issuecomment-1136550186

2022-05-25 02:33 UTC, jansel approved these changes

2022-05-25 04:03 UTC, merged