[WIP][inductor] Update aliased buffer writes with more accurate dependencies
pytorch/torchdynamo pull request #483
Opened 2022-06-29 18:41 UTC by desertfire

2022-06-29 18:42 UTC, jansel approved these changes

2022-06-29 22:41 UTC, desertfire commented
Still one pending failure on `test_slice_mutation2_cpu`, where this PR broke the assumption that the input and output pointers are not overlapped.

2022-06-30 17:00 UTC, jansel requested changes

2022-06-30 17:04 UTC, desertfire commented on tests/test_torchinductor.py
> +    @unittest.skip("")
Oh, my mistake. It fails locally for me without this PR. Let me drop it.

2022-06-30 17:27 UTC, desertfire commented on torchinductor/scheduler.py
> +            write_dep = self.scheduler.name_to_node[name].read_writes.writes
If I understand you question correctly, the existing code achieve this strong order by inserting dependencies between all the previous aliased def and use, where previous 'use' could really be a def itself. 
```
            for alt_name in node.get_mutations():
                alt_name = rename(alt_name)
                # this node must run after the prior writer
                add_user(alt_name, node)
                node.add_mutation_dep(alt_name)
                for other_node in name_to_users[alt_name]:
                    # this node must run after all prior readers
```

It passes `test_slice_mutation1` and `test_slice_mutation2`. Let me know if you have any other specific test cases in mind.

2022-07-06 15:26 UTC, closed without merging