Fix several bugs of running torchbench with unspec int/float
pytorch/torchdynamo pull request #539
Opened 2022-07-10 04:46 UTC by yanboliang

I run torchbench with unspec int/float by default and found several bugs. This PR will fix these easy bugs and add workaround to ensure torchbench is still green. The two models which need work around has been track at [here](https://github.com/pytorch/torchdynamo/issues/538).

2022-07-10 05:07 UTC, yanboliang commented on torchdynamo/variables/builder.py
> +            352,  # Work around for Super_SloMo
The new added above is common constants from torchbench, the bellow three lines are workaround for the two failed models.

2022-07-10 17:14 UTC, jansel approved these changes

2022-07-10 20:18 UTC, jansel requested changes
Since this doesn't fix all the bugs lets revert this PR with https://github.com/pytorch/torchdynamo/pull/546

Then merge again once torchbench works.

2022-07-17 02:41 UTC, jansel commented
Reopen this when it is ready for review

2022-07-17 02:41 UTC, closed without merging