Disable built-in functionalization when we use functorch's functionalization
pytorch/torchdynamo pull request #568
Opened 2022-07-13 13:21 UTC by ezyang

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

2022-07-13 14:58 UTC, jansel requested changes

2022-07-13 14:58 UTC, jansel commented on torchdynamo/optimizations/normalize.py
> +        if not functorch._src.config.use_functionalize:
I think this check should go here instead:
https://github.com/pytorch/torchdynamo/blob/bb60ba951dcccb8de5aef6e930ef6cc7a30b24e3/torchdynamo/optimizations/training.py#L32

So it only affect AOT Autograd (and not other backends).

2022-07-16 20:19 UTC, anijain2305 commented
Duplicate - https://github.com/pytorch/torchdynamo/pull/593. That PR is basically Jason's suggestion.

2022-07-17 00:57 UTC, ezyang commented
closing in favor of @anijain2305's version

2022-07-17 00:57 UTC, closed without merging