Split indexing clean
pytorch/torchdynamo pull request #685
Opened 2022-07-31 04:58 UTC by pyjhzwh

For fused kernels, although it is guaranteed that the reads from and writes to the same region of the buffer by checking the MemoryDep. But for the case when the 
`buf1 = buf0.permute(0,3,1,2); buf2 = buf1` where buf0 is NHWC layout and buf1 and buf2 is NCHW layout.
the indexing of `tl.store` to buf2 maybe wrong due to indexing mismatch of buf1.
Instead of creating a new RangeTreeEntry, we will try to split the current range on the existing RangeTreeEntries.
See the example below

Before (wrong):
```
@triton.jit
def kernel4(in_ptr0, in_ptr1, in_ptr2, in_ptr3, out_ptr0, out_ptr1, out_ptr2, out_ptr3, ks0, xnumel, XBLOCK : tl.constexpr):
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK])
    xmask = xindex < xnumel
    x4 = xindex
    x0 = xindex % 64
    x0_next = xindex // 64
    x1 = x0_next % 3025
    x1_next = x0_next // 3025
    x2 = x1_next
    x5 = xindex % 193600
    x5_next = xindex // 193600
    x6 = x5_next
    tmp0 = tl.load(in_ptr0 + x4 + tl.zeros([XBLOCK], tl.int32), xmask)
    tmp1 = tl.load(in_ptr1 + x0 + tl.zeros([XBLOCK], tl.int32), xmask) # NHWC layout
    tmp3 = tl.load(in_ptr2 + x4 + tl.zeros([XBLOCK], tl.int32), xmask)
    tmp5 = tl.load(in_ptr3 + x4 + tl.zeros([XBLOCK], tl.int32), xmask)
    tmp2 = tmp0 + tmp1
    tmp4 = tmp3 + tmp1 # NHWC layout
    tmp6 = tmp5 + tmp1
    tl.store(out_ptr0 + x1 + (3025*x0) + (387200*x2) + tl.zeros([XBLOCK], tl.int32), tmp2, xmask)
    tl.store(out_ptr1 + x1 + (3025*x0) + (387200*x2) + tl.zeros([XBLOCK], tl.int32), tmp4, xmask) # NCHW layout
    tl.store(out_ptr2 + x1 + (3025*x0) + (387200*x2) + tl.zeros([XBLOCK], tl.int32), tmp6, xmask)
    # wrong!! because it is equivalent to `tl.store(out_ptr3 + x0 + 64*x1 +  (387200*x6), tmp4)`, the indexing is wrong
    # we would expect `tl.store(out_ptr3 + x1 + (3025*x0) + (387200*x2), tmp6)`
    tl.store(out_ptr3 + x5 + (387200*x6) + tl.zeros([XBLOCK], tl.int32), tmp4, xmask) 
```
The RangeTree looks like this:
>>>
                    Root
                  /         \
            x0: 64      x5: 193600 (equivalent to x0 + 64*x1)
                /              \
         x1 : 3025       x6: s0
                |  
              x2: s0
>>>

After:
```
@triton.jit
def kernel4(in_ptr0, in_ptr1, in_ptr2, in_ptr3, out_ptr0, out_ptr1, out_ptr2, out_ptr3, ks0, xnumel, XBLOCK : tl.constexpr):
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK])
    xmask = xindex < xnumel
    x4 = xindex
    x0 = xindex % 64
    x0_next = xindex // 64
    x1 = x0_next % 3025
    x1_next = x0_next // 3025
    x2 = x1_next
    x5 = x1 + (3025*x0)
    tmp0 = tl.load(in_ptr0 + x4 + tl.zeros([XBLOCK], tl.int32), xmask)
    tmp1 = tl.load(in_ptr1 + x0 + tl.zeros([XBLOCK], tl.int32), xmask)
    tmp3 = tl.load(in_ptr2 + x4 + tl.zeros([XBLOCK], tl.int32), xmask)
    tmp5 = tl.load(in_ptr3 + x4 + tl.zeros([XBLOCK], tl.int32), xmask)
    tmp2 = tmp0 + tmp1
    tmp4 = tmp3 + tmp1
    tmp6 = tmp5 + tmp1
    tl.store(out_ptr0 + x1 + (3025*x0) + (387200*x2) + tl.zeros([XBLOCK], tl.int32), tmp2, xmask)
    tl.store(out_ptr1 + x1 + (3025*x0) + (387200*x2) + tl.zeros([XBLOCK], tl.int32), tmp4, xmask)
    tl.store(out_ptr2 + x1 + (3025*x0) + (387200*x2) + tl.zeros([XBLOCK], tl.int32), tmp6, xmask)
    tl.store(out_ptr3 + x5 + (387200*x2) + tl.zeros([XBLOCK], tl.int32), tmp4, xmask)
```

The RangeTree looks like this:
>>>
                    Root
                  /         \
            x0: 64      x5 (AliasedEntry)
                /                 = x1 + 3025 * x0 (it is decided in cse.store_cache)
               /             /
         x1 : 3025        /
                |        /
                |     /
                x2: s0
>>>

2022-08-01 20:25 UTC, jansel commented
I wonder if we could implement this in a simpler way by adding an extra layer of caching.

If you rewrite the indexing to all be in terms of `xindex`:
```
    x0 = xindex % 64            # ir.ModularIndexing(xindex, 1, 64)
    x1 = (xindex // 64) % 3025  # ir.ModularIndexing(xindex, 64, 3025)
    x2 = xindex // 193600       # ir.IndexingDev(xindex, 193600)
    x5 = xindex % 193600        # ir.ModularIndexing(xindex, 1, 193600)
    x6 = xindex // 193600       # ir.IndexingDev(xindex, 193600)
```
Which should allow x2 and x6 to get merged with a simple dict cache.
```
expr_in_terms_of_xindex = ...
cache[expr_in_terms_of_xindex] = "x2"
```

2022-08-02 01:06 UTC, pyjhzwh commented
> I wonder if we could implement this in a simpler way by adding an extra layer of caching.
> 
> If you rewrite the indexing to all be in terms of `xindex`:
> 
> ```
>     x0 = xindex % 64            # ir.ModularIndexing(xindex, 1, 64)
>     x1 = (xindex // 64) % 3025  # ir.ModularIndexing(xindex, 64, 3025)
>     x2 = xindex // 193600       # ir.IndexingDev(xindex, 193600)
>     x5 = xindex % 193600        # ir.ModularIndexing(xindex, 1, 193600)
>     x6 = xindex // 193600       # ir.IndexingDev(xindex, 193600)
> ```
> 
> Which should allow x2 and x6 to get merged with a simple dict cache.
> 
> ```
> expr_in_terms_of_xindex = ...
> cache[expr_in_terms_of_xindex] = "x2"
> ```

The cache would work to reduce recomputation of indexing. But the main reason for split indexing is for triton convolution, the output layout is channel-last, for output size as arg0 [N, H, W, C] = [s0, 55, 55, 64]
Assume buf0 = arg0.to(memory_layout=torch.contigous); buf1 = buf0.clone(); They will be fused into 1 kernel
```
x0 = xindex % 64          
x1 = (xindex // 64) % 3025  
x2 = xindex // 193600 
x5 = xindex % 193600 (equivalent to x5 = x0 + x1 *64)
x6 = xindex // 193600
tmp = tl.load(in_ptr0 + xindex) # read from conv arg0 N(HW)C layout
tl.store(out_ptr0 + x1 + 3025 * x0 + 193600 * x2, tmp) # write to buf0 NC(HW) layout
tl.store(out_ptr1 + x5 + 193600 * x6, tmp) # want to write to buf1 NC(HW) layout, but wrongly write to NHWC layout
```
This is because the indexing `x5 = xindex % 193600` is generated unware of the existing RangeTree (x0:64 -> x1: 3025-> x2: s0). To buf1's view, it reads from buf0 in NCHW layout and write to buf1 NCHW layout, and generate the x5 and x6 indexing code. But because of `cse.store_cache[arg0] = tmp`, buf1 store `tmp` value, but still use the x5, x6 indexing, which is wrong. The correct indexing should be `x5 = x1 + 3025 * x0; x6 = x2`.

The use case for this PR may not be clear when all layout are contiguous by default. But if convolution use the NHWC layout, the torchbench "Background_Matting"'s output is wrong

2022-08-02 03:52 UTC, jansel commented
@pyjhzwh does this commit address your issue:
https://github.com/jansel/torchdynamo/commit/026b68b9e41ee263a7a6bb582013467eacc970c4

It gets rid of the "tree" part of range trees (children is replaced with a flat list of entries using the cache structure I described).

You can ignore the `vars_and_sizes` stuff, that is related to #688

2022-08-02 17:07 UTC, pyjhzwh commented
> @pyjhzwh does this commit address your issue: [jansel@026b68b](https://github.com/jansel/torchdynamo/commit/026b68b9e41ee263a7a6bb582013467eacc970c4)
> 
> It gets rid of the "tree" part of range trees (children is replaced with a flat list of entries using the cache structure I described).
> 
> You can ignore the `vars_and_sizes` stuff, that is related to #688

I think it could not solve the issue of the wrong indexing. I think jansel@026b68b could simply the indexing expression, but it won't change the formula it represents
Current indexing ( wrong)
x0 = xindex % 64          
x1 = (xindex // 64) % 3025  
x2 = xindex // 193600 
x5 = xindex % 193600 (equivalent to **x5 = x0 + x1 \* 64**)
x6 = xindex // 193600

What we want (correct)
 x0 = xindex % 64          
x1 = (xindex // 64) % 3025  
x2 = xindex // 193600 
**x5 = x1 + 3025 * x0**
x6 = xindex // 193600

The `x5 =  x1 + 3025 * x0` could not be decided at the time when we construct RangeTree until we check store_cache: https://github.com/pytorch/torchdynamo/pull/685/files#diff-1dc2b4658200030b6f1adf8b0345586974d98dff1bcd328612f40c4b924e20bbR653

2022-08-02 21:03 UTC, jansel requested changes
we talked about this in person.  should try to fix root cause.

2022-08-03 00:30 UTC, closed without merging