Throw a RuntimeError when accuracy comparison fails
pytorch/torchdynamo pull request #958
Opened 2022-08-22 17:41 UTC by desertfire

Summary: Without a RuntimeError, we still writes speedup numbers to the
output .cvs file, which causes CI not catching the failures, see an
example at
https://app.circleci.com/pipelines/github/pytorch/torchdynamo/1363/workflows/d32a7326-01e4-4a83-a283-3e4cab0fa203/jobs/1848

2022-08-22 17:43 UTC, desertfire commented on benchmarks/common.py
> +                        raise RuntimeError("INCORRECT - Variation in Eager runs itself")
I not very sure if we want to relax this one.

2022-08-22 17:45 UTC, desertfire commented
@anijain2305 , this PR will likely drag down our pass rate and possibly perf number as well.

2022-08-22 17:46 UTC, jansel requested changes
Due to different implementation of dropout (and other things) some variations are expected.

We have `self.args.skip_accuracy_check` which already controls this behavior.  If skip_accuracy_check is true we raise an error, otherwise we should ignore the difference.

2022-08-22 17:54 UTC, desertfire commented
> Due to different implementation of dropout (and other things) some variations are expected.
> 
> We have `self.args.skip_accuracy_check` which already controls this behavior. If skip_accuracy_check is true we raise an error, otherwise we should ignore the difference.

Ok, I guess we only need this for the inference comparison and it does work without this PR, https://app.circleci.com/pipelines/github/pytorch/torchdynamo/1408/workflows/40ca691c-87bf-47d9-b7c7-018647fa8e36/jobs/1941

Let me close this one.

2022-08-22 17:54 UTC, closed without merging

2022-08-23 01:04 UTC, jansel commented
Just set `skip_accuracy_check=False` in CI.